### ISSUE TITLE
Height of Navbar differs between Index and Referenzen / Jobs / Blog

### ISSUE THREAD

**Issue by Lutzifer** [num42/n42-web-middleman#30]
Especially visible in Firefox:

<img width="579" alt="screen shot 2018-06-14 at 16 42 19" src="https://user-images.githubusercontent.com/194417/41423631-1c839d80-6ffc-11e8-8561-7fc7ace35b2b.png">

**Comment by HannesHeuberger** [comment]
removed .mobile-nav class from _nav partial
